# -*- mode: ruby -*-
# vi: set ft=ruby :

#INSTALL PLUGINS
required_plugins = %w( vagrant-hostmanager )
required_plugins.each do |plugin|
  exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(" ")}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end

#LOCAL VAGRANT CONFIG
localconfig = File.read '1_local-vagrant-config.rb'
eval localconfig

Vagrant.configure(2) do |config|

  #BOX
  config.vm.box = "debian/jessie64"
  config.vm.box_check_update = true

  #NETWORKING
  config.vm.network "private_network", ip: LOCAL_ARGS["guest_ip"]
  config.ssh.forward_agent = true

  # Forward any ports necessary.
  # config.vm.network "forwarded_port", guest: 1080, host: 10001

  #SYNC
  config.vm.synced_folder "../", "/var/www/", type: "nfs"

  #HOSTNAME CONFIG(requires vagrant-hostmanager)
  config.vm.hostname = LOCAL_ARGS["guest_hostname"]
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  #PROVIDER (AKA VM)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 2
  end

  # RUN BOOTSTRAP
  config.vm.provision "shell",
    path: "vagrant-bootstrap.sh",
    privileged: false,
    :args => [
      LOCAL_ARGS["guest_ip"],
      LOCAL_ARGS["guest_hostname"],
      LOCAL_ARGS["app_root"],
      LOCAL_ARGS["doc_root"]
    ]

end

